# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fm < Formula
  desc "Keep those files organized"
  homepage "https://github.com/knipferrc/fm"
  version "0.15.2"

  if OS.mac? && Hardware::CPU.intel?
	url "https://github.com/knipferrc/fm/releases/download/v0.15.2/fm_0.15.2_darwin_amd64.tar.gz"
	sha256 "3e7bb10358f83228a4c6ecb6e207e192b662960dd2101e5f2f6b22fb8beb21f0"
  end
  if OS.mac? && Hardware::CPU.arm?
	url "https://github.com/knipferrc/fm/releases/download/v0.15.2/fm_0.15.2_darwin_arm64.tar.gz"
	sha256 "d6d593679451ba76f3c71c8c97eed7d919e34da37bf3bb2a20e14fe8ed9ea506"
  end
  if OS.linux? && Hardware::CPU.intel?
	url "https://github.com/knipferrc/fm/releases/download/v0.15.2/fm_0.15.2_linux_amd64.tar.gz"
	sha256 "b8355f2dbd8fa3b02c29cec0743eb082b5c2ba32c2c73a05076d614e6b431f79"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
	url "https://github.com/knipferrc/fm/releases/download/v0.15.2/fm_0.15.2_linux_armv7.tar.gz"
	sha256 "62e1a680e41191512fdffbb4e94bc7542c99d6de9998ac2158a6850fb8a6aabb"
  end

  def install
	bin.install "fm"
  end
end